# Generated by Django 2.1 on 2018-09-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mineral',
            name='image_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mineral',
            name='image_filename',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
    ]
